"""empty message

Revision ID: 025b49261ef6
Revises: 
Create Date: 2021-04-19 22:35:55.106101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025b49261ef6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('title'),
    sa.UniqueConstraint('title')
    )
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry time', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readings')
    op.drop_table('book')
    # ### end Alembic commands ###
