"""Adding batV column

Revision ID: bfd1925154f8
Revises: 025b49261ef6
Create Date: 2021-10-03 20:46:25.611292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfd1925154f8'
down_revision = '025b49261ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='sensortest')
    op.drop_table('sensortest')
    op.add_column('readings', sa.Column('batteryV', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readings', 'batteryV')
    op.create_table('sensortest',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entryTime', mysql.TIMESTAMP(), nullable=True),
    sa.Column('unitID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sensorID', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('value', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'sensortest', ['id'], unique=True)
    # ### end Alembic commands ###
